import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import '@/shared/styles/globals.css';
import '@/shared/styles/tailwind.colors.css';
import Header from '@/widgets/Header';
import React from 'react';

const notoSans = Noto_Sans({
	variable: '--font-noto-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${notoSans.className} antialiased bg-black-800`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
